name: Patch Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Set up GitHub Actions token
      run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/actions/permissions \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{"permissions":{"pull-requests":{"admin":true}},"resources":{"actions":{"enabled":true},"repositories":{"allowed":true}}}'

    - name: Install dependencies
      run: npm ci

    - name: Configure Git
      run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

    - name: Check working directory status
      run: |
          if ! git diff-index --quiet HEAD --; then
            git stash
          fi

    - name: Increment version
      id: increment_version
      run: |
          NEW_VERSION=$(npm version patch -m "💪 Increase Version to %s")
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "name=NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Push changes
      run: |
          git push