name: Update Version

on:
  push:
    branches:
      - pre-patch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Get current version
      id: get_version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "::set-output name=version::$VERSION"

    - name: Increment version
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        MINOR=$(echo $VERSION | cut -d. -f2)
        NEW_VERSION="$(echo $VERSION | sed "s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1.\2.$((MINOR+1)).0-rc.1/")"
        echo "::set-output name=new_version::$NEW_VERSION"

    - name: Update package.json
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        NEW_VERSION=${{ steps.increment_version.outputs.new_version }}
        sed -i "s/\"version\":\s\"$VERSION\"/\"version\":\s\"$NEW_VERSION\"/g" package.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json
        git commit -m "Update version to $NEW_VERSION"
        git push
