name: Despliegue a Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar dependencias
      run: npm install

    - name: Compilar aplicación
      run: npm run build

    - name: Empaquetar aplicación
      run: zip -r app.zip .

    - name: Desplegar a Render
      uses: render/deploy@v1
      with:
        service: Test
        environment: production
        token: ${{ secrets.RENDER_TOKEN }}
        archive: app.zip
