name: Patch Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Extract current version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "$VERSION" > version.txt

    - name: Update version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        MINOR=$(echo $VERSION | cut -d. -f2)
        NEW_VERSION="$(echo $VERSION | sed "s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1.\2.$((MINOR+1)).0-rc.1/")"
        echo "$NEW_VERSION" > new_version.txt

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json version.txt
        git commit -m "Update version to $NEW_VERSION"
        git remote set-url origin https://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@github.com/${{ github.repository }}.git
        git push origin main
