name: Backend Render Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 14.21

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Render
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: rnd_PQn8Ert7QUo7MBQP5kW85qGOPkpI
          github-token: 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
          service-id: srv-cn017h7qd2ns73cffs30
          retries: 20
          wait: 16000
          sleep: 30000

