name: Versioning

on:
  push:
    branches:
      - '**'
    paths:
      - '**'

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Set up Git identity
      run: |
          git config user.email "bedoyasergio3@gmail.com"
          git config user.name "SergioABH"

    - name: Versioning
      id: versioning
      run: |
        git fetch --tags
        current_version=$(git describe --tags --abbrev=0)
        if [[ $current_version == *-* ]]; then
          version_type=prerelease
        elif [[ $current_version == *.*.* ]]; then
          version_type=patch
        else
          version_type=minor
        fi
        new_version=$(npm version $version_type)
        git tag $new_version
        git push origin $new_version
      