name: Backend Render Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: '123'
          POSTGRES_DB: 'postgres'
        options: --health-interval 20s --health-timeout 10s --health-retries 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 14.21

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL to be ready
        run: sleep 30

      - name: Set up PostgreSQL
        run: |
          sleep 10
          psql -h localhost -U 'postgres' -c "CREATE DATABASE 'postgres';"
          psql -h localhost -U 'postgres' 'postgres' < db/schema.sql
          psql -h localhost -U 'postgres' 'postgres' < db/test_data.sql

      - name: Run Jest tests
        run: npm run test

      - name: Deploy to Render
        if: success()
        run: |
          curl -X POST \
            https://api.render.com/deploy/${{ secrets.BACKEND_ID }}?key=2Cau52g5CZE \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"gitCommit": "${{ github.sha }}"}'